# Generated by Django 4.0.3 on 2022-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dato_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(related_name='estudiantes', to='dato_cursos.curso'),
        ),
    ]
